---


title       : Pregnancy Weight Gain Calculator
subtitle    : A Shiny App to calculate the optimal weight gain during pregnancy
author      : D. E. 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : standalone
knit        : slidify::knit2slides
github:
     user:Riccina
     repo:Riccina.github.io
---
    
<q>How much weight a woman should gain during pregnancy depends 
on how much she weighed before conceiving and how appropriate 
that weight is for her height as expressed by the "body mass index," or BMI</q>

--- 

## Guidelines for pregnancy weight gain

<style>
strong {
  font-weight: bold;
}
</style>

The guidelines for pregnancy weight gain are issued by the Institute of Medicine (IOM).

> - A woman with a **healthy pre-pregnancy weight** relative to her height (BMI of 18.5 to 24.9), should gain between between 16kg and 24kg.  
> - An **underweight** woman (BMI below 18.5), should gain between 12.5kg and 18kg.  
> - An **overweight** woman (BMI of 25 to 29.9), should gain between 14kg and 23kg.  
> - An **obese** woman (BMI of over 30), should gain between 11kg and 19kg.  

---

## How does the calculator work

<style>
em {
  font-style: italic
}
</style>

The calculator takes 2 inputs:

- *Pre-pregnancy height (in cm)*
- *Pre-pregnancy weight (in kg)*

The user selects the relevant values using a sidebar panel.

The user's BMI is calculated in the main panel using the following formula:

```{r}
pBMI<-function(Weight,Height) {
        if (Weight==0 | Height==0) return(NA)
        else  return(round(Weight/(Height/100)^2,1))
}
```

The user's recommended pregnancy weight gain is printed out below the BMI figure.

---

<br><br>
**Thank you**
<br><br>

Visit the following URL to see the finished product  

[Pregnancy Weight Gain Calculator](https://daelia.shinyapps.io/PregnancyWeight/)  
<br><br>

The code is also available on github  

[Github Code](https://github.com/Riccina/Developing-Data-Products/)  
<br><br>

For more information on weight gain during pregnancy visit  

[Weight Gain During Pregnancy Reexamining the Guidelines](http://iom.edu/Reports/2009/Weight-Gain-During-Pregnancy-Reexamining-the-Guidelines.aspx)


